/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}

rootProject.name = "Boomslang"

include("app")
