/*
 * This file was generated by the Gradle 'init' task.
 */
val BOOMSLANG_HOME: String? = System.getenv("BOOMSLANG_HOME")

plugins {
    java
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("checkstyle")
    id("jacoco")
    // id("io.freefair.lombok") version "8.4"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
//    flatDir {
//        dirs("../resources")
//    }
}

dependencies {
    // Core libraries
    implementation("com.google.code.gson:gson:2.10.1")
    implementation("com.google.guava:guava:32.1.3-jre")
    implementation("org.roaringbitmap:RoaringBitmap:0.9.45")
    
    // Logging
    implementation("org.slf4j:slf4j-api:2.0.9")
    implementation("org.apache.logging.log4j:log4j-slf4j2-impl:2.21.1")
    implementation("org.apache.logging.log4j:log4j-core:2.21.1")
    
    // Utilities
    implementation("net.openhft:zero-allocation-hashing:0.8")
    implementation("com.fasterxml.jackson.core:jackson-core:2.15.2")
    implementation("com.opencsv:opencsv:5.8")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.15.2")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.2")
    implementation("us.bpsm:edn-java:0.7.1")
    implementation("commons-cli:commons-cli:1.6.0")
    implementation("org.apache.commons:commons-lang3:3.13.0")
    implementation("org.javatuples:javatuples:1.2")
    
    // Graph processing
    implementation("org.jgrapht:jgrapht-core:1.5.2")
    
    // External JARs
    implementation(files("../resources/monosat.jar"))
    
    // Solvers
    implementation("io.github.tudo-aqua:z3-turnkey:4.8.9")
    
    // Database
    implementation("com.pingcap.tikv:tikv-client:3.2.2")
//    implementation("org.nd4j:nd4j-native-platform:1.0.0-M2.1")
    implementation("org.nd4j:nd4j-cuda-11.6:1.0.0-M2.1") // Replace with the correct CUDA version and latest ND4J version
// https://mvnrepository.com/artifact/org.nd4j/nd4j-cuda-11.2-platform
    implementation("org.nd4j:nd4j-cuda-11.6-platform:1.0.0-M2.1")
    
    // Testing
    testImplementation("org.testng:testng:7.8.0")
    
    // Lombok
    compileOnly("org.projectlombok:lombok:1.18.32")
    annotationProcessor("org.projectlombok:lombok:1.18.32")
}

group = "khoury-srg"
version = "1.0-SNAPSHOT"
description = "Boomslang"

java { 
    toolchain { 
        languageVersion.set(JavaLanguageVersion.of(17)) 
    } 
}

// Checkstyle configuration
checkstyle {
    toolVersion = "10.12.4"
    configFile = file("../style/google_checks.xml")
    maxWarnings = 0
}

// JaCoCo configuration
jacoco {
    toolVersion = "0.8.11"
}

tasks.jacocoTestReport {
    dependsOn(tasks.test) // Run tests before generating report

    reports {
        xml.required.set(true)   // For CI/CD tools like GitHub Actions
        html.required.set(true)  // For human reading
        csv.required.set(true)   // For badge generators and simple parsers
    }
}

// Optional: Coverage verification rules (NOT failing build)
tasks.jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.20.toBigDecimal()  // Start with current 20% as baseline
            }
        }
    }
}

// JAR configuration
tasks.jar {
    manifest {
        attributes["Main-Class"] = "main.Main"
    }
}

// Shadow JAR configuration
tasks.shadowJar {
    archiveClassifier.set("")
    archiveBaseName.set("boomslang")
    archiveVersion.set("")
    manifest {
        attributes["Main-Class"] = "main.Main"
    }
    mergeServiceFiles()
}

// Custom Shadow JAR for unsat search
val shadowJarA by tasks.creating(com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar::class) {
    archiveClassifier.set("a")
    archiveBaseName.set("boomslang_unsat_search")
    archiveVersion.set("")
    manifest {
        attributes["Main-Class"] = "main.Main"
    }
    configurations = listOf(project.configurations.runtimeClasspath.get())
}

// Build configuration
tasks.build {
    dependsOn(tasks.named("shadowJar"), tasks.named("shadowJarA"))
}

//val shadowJarB by tasks.creating(com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar::class) {
//    archiveClassifier.set("b")
//    from(sourceSets.main.get().output)
//    manifest {
//        attributes["Main-Class"] = "main.CheckSubgraph"
//    }
//    configurations = listOf(project.configurations.runtimeClasspath.get())
//}
//
//tasks.shadowJar {
//    archiveClassifier.set("b") // Removes the "-all" suffix from the output JAR name
//    manifest {
//        attributes["Main-Class"] = "CheckSubgraph" // Specify the main class
//    }
//    mergeServiceFiles()
//}

//tasks.build {
//    dependsOn(shadowJarA, shadowJarB)
//}

//tasks.withType<org.gradle.api.tasks.compile.JavaCompile> {
//    options.compilerArgs.add("-Xlint:deprecation")
//}

//tasks.named<Test>("test") {
//    useTestNG()
//
//    jvmArgs = listOf("-Djava.library.path=/usr/local/lib", "-Dlog4j.configurationFile=../log4j2.xml", "-Xmx10g", "-Xms10g")
//
//    testLogging {
//        events("started", "passed", "skipped", "failed")
//        showStandardStreams = true // Show the standard output and error streams
//        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
//        showExceptions = true
//        showCauses = true
//        showStackTraces = true
//    }
//}

// Test configuration
tasks.test {
    useTestNG {
        // Prints TestNG's default footer summary
        useDefaultListeners = true
    }
    jvmArgs = listOf(
        "-Djava.library.path=/usr/local/lib",
        "-Dlog4j.configurationFile=../log4j2.xml",
        "-Xmx10g",
        "-Xms10g"
    )

    // Generate JaCoCo coverage report after tests
    finalizedBy(tasks.jacocoTestReport)
    
    testLogging {
        events("started", "passed", "skipped", "failed")
        showStandardStreams = true
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showExceptions = true
        showCauses = true
        showStackTraces = true
    }

    // One clean summary at the very end of the whole run
    afterSuite(KotlinClosure2<TestDescriptor, TestResult, Unit>({ desc, result ->
        if (desc.parent == null) { // root suite
            println("\n===== TEST SUMMARY =====")
            println("Total:   ${result.testCount}")
            println("Passed:  ${result.successfulTestCount}")
            println("Failed:  ${result.failedTestCount}")
            println("Skipped: ${result.skippedTestCount}")
            val pct = if (result.testCount > 0) 100.0 * result.successfulTestCount / result.testCount else 0.0
            println("Success rate: %.1f%%".format(pct))
            println("=========================\n")
        }
    }))
}
