package tools.anomaly_injector;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import org.apache.commons.io.FileUtils;

import common.Key;
import common.binaryhistory.Mop;
import common.binaryhistory.OP_TYPE;
import common.binaryhistory.SessionHistory;
import lombok.SneakyThrows;
import util.MapFactory;

public abstract class UnsatCoreInjector {
    public abstract Set<Integer> injectUnsatCores(Map<Integer, SessionHistory> m, int numOfUnsatCores);

    @SneakyThrows
    protected Map<Integer, SessionHistory> load(Path historyFolder) {
        File dir = historyFolder.toFile();
        File[] logFiles = dir.listFiles();
        Map<Integer, SessionHistory> sessionHistoryMap = new HashMap<>();

        if (logFiles != null) {
            for (File logFile : logFiles) {
                // filter
                if (!logFile.getName().startsWith("T") || !logFile.getName().endsWith(".log")) {
                    continue;
                }

                SessionHistory sessionHistory = SessionHistory.loadFromFile(logFile);
                String fileName = logFile.getName();
                int threadId = Integer.parseInt(fileName.substring(1, fileName.length() - 4));
                sessionHistoryMap.put(threadId, sessionHistory);
            }
        }

        return sessionHistoryMap;
    }

    protected Mop createMop(OP_TYPE op_type, Key key, Key value) {
        return new Mop(op_type, key, value, null,
                false, false, null, null, null);
    }

    @SneakyThrows
    protected void dump(Map<Integer, SessionHistory> m,
            Set<Integer> targetTids,
            String srcFolder,
            String dstFolder) {
        if (!Files.exists(Path.of(dstFolder))) {
            new File(dstFolder).mkdirs();
        } else {
            FileUtils.deleteDirectory(new File(dstFolder));
        }

        for (var tid : m.keySet()) {
            if (targetTids.contains(tid)) {
                // if this session is generated by the injector,
                // create a new file for it
                SessionHistory sessionHistory = m.get(tid);
                Path path = Path.of(dstFolder.toString(), "J" + tid + ".log");
                sessionHistory.write2Files(path);
            } else {
                // if this session exists in original history, just copy it.
                FileUtils.copyFile(
                        new File(srcFolder + "/J" + tid + ".log"),
                        new File(dstFolder + "/J" + tid + ".log"));
            }
        }
    }
}
